package es.uniovi.raul.sies2csv.cli;

import picocli.CommandLine.*;

// CHECKSTYLE:OFF

@Command(name = "sies2csv", showDefaultValues = true, mixinStandardHelpOptions = true, usageHelpAutoWidth = true, description = Messages.DESCRIPTION, customSynopsis = Messages.USAGE, footer = Messages.CREDITS, versionProvider = PomVersionReader.class)
public class Arguments {

    @Parameters(defaultValue = "alumnosMatriculados.xls", description = "The excel file generated by sies with the list of students and their groups (optional).")
    public String studentsFile;

    @Option(names = "-o", defaultValue = "new-roster.csv", description = "The output file where the list of students will be saved.")
    public String outputFile;

    @Option(names = "-s", defaultValue = "schedule.csv", description = "The file listing the groups to be considered for the teacher. Groups not present in this file will not be considered.")
    public String groupsFile;

}

class Messages {
    static final String DESCRIPTION = """

            Converts the Excel file generated by SIES (the academic management system of the University of Oviedo) to a CSV file. Optionally, filters the students by the groups assigned to the teacher.

            For more information, visit: https://github.com/raul-izquierdo/sies2csv
            """;

    static final String USAGE = "\n\tjava -jar sies2csv.jar [OPTIONS] [<studentsFile>]";

    static final String CREDITS = """

            Escuela de Ingenieria Informatica. Universidad de Oviedo.
            Raúl Izquierdo Castanedo (raul@uniovi.es)
            """;

}

class PomVersionReader implements IVersionProvider {
    public String[] getVersion() throws Exception {
        return new String[] { Arguments.class.getPackage().getImplementationVersion() };
    }
}
