package es.uniovi.raul.sies2csv.input.sies;

import static java.lang.String.*;
import static org.apache.poi.ss.usermodel.CellType.*;
import static org.apache.poi.ss.usermodel.WorkbookFactory.*;

import java.io.*;
import java.nio.file.*;
import java.util.*;

import org.apache.poi.ss.usermodel.*;

import es.uniovi.raul.sies2csv.main.IssuesCounter;

/**
 * Loads student data from a SIES Excel file and converts it into a list of Student objects.
 */
public class SiesExcelLoader {

    // Excel cell positions (0-based)
    private static final int HEADERS_ROW = 9; // Aquí deberían estar los encabezados (fila 10 en Excel)
    private static final int FIRST_STUDENT_ROW = HEADERS_ROW + 1; // Aquí debería estar el primer estudiante (fila 11 en Excel)

    private static final String NAME_HEADER = "Alumno";
    private static final int NAME_COLUMN = 2; // Aquí debería estar la columna "Alumno" - Column C

    private static final String EMAIL_HEADER = "Email";
    private static final int EMAIL_COLUMN = 3; // Aquí debería estar la columna "Email" - Column D

    private static final String LABORATORY_HEADER = "Prácticas de Laboratorio";
    private static final int LABORATORY_COLUMN = 10; // Aquí debería estar la columna "Prácticas de Laboratorio" - Column K

    private static final String LAB_PREFIX = "Prácticas de Laboratorio-";

    public static final List<Student> loadStudents(Path file, IssuesTracker issuesTracker)
            throws InvalidStudentFormatException, IOException {

        try (InputStream inputStream = Files.newInputStream(file)) {

            return loadStudents(inputStream, issuesTracker);

        } catch (InvalidStudentFormatException e) {
            throw new InvalidStudentFormatException(String.format(
                    "'%s' is not a valid excel file generated by the SIES system. %s%nPlease check the format and try again.",
                    file, e.getMessage()));
        }
    }

    public static final List<Student> loadStudents(InputStream inputStream)
            throws InvalidStudentFormatException, IOException {
        return loadStudents(inputStream, new IssuesCounter());
    }

    public static final List<Student> loadStudents(InputStream inputStream, IssuesTracker issuesTracker)
            throws InvalidStudentFormatException, IOException {

        try (Workbook workbook = create(inputStream)) {

            Sheet sheet = workbook.getSheetAt(0); // The first sheet should contain the student data

            // 1. Validate that the file is a SIES excel file by checking the headers
            validateSiesFormat(sheet);

            // 2. Parse the sheet and extract student data
            return readSheet(sheet, issuesTracker);
        }
    }

    /**
    * Validates that the file is a SIES excel file.
    * Checks that the headers are in the expected positions and have the correct values.
    */
    private static void validateSiesFormat(Sheet sheet) throws InvalidStudentFormatException {
        checkHeader(sheet, NAME_COLUMN, "C", NAME_HEADER);
        checkHeader(sheet, EMAIL_COLUMN, "D", EMAIL_HEADER);
        checkHeader(sheet, LABORATORY_COLUMN, "K", LABORATORY_HEADER);
    }

    /**
     * Checks that the header row has the expected value at the given column.
     */
    private static void checkHeader(Sheet sheet, int column, String columnLetter, String expectedHeader)
            throws InvalidStudentFormatException {

        Row headerRow = sheet.getRow(HEADERS_ROW); // Row 10 (0-based index)
        String value = getCellValue(headerRow, column).orElse("");

        if (!expectedHeader.equalsIgnoreCase(value))
            throw new InvalidStudentFormatException(
                    format("Expected header '%s' not found at column %s, row %d. Found: '%s'", expectedHeader,
                            columnLetter, HEADERS_ROW + 1, value));
    }

    /**
     * Reads the Excel sheet starting from the specified row and processes each row.
     */
    private static List<Student> readSheet(Sheet sheet, IssuesTracker issuesTracker)
            throws InvalidStudentFormatException {

        List<Student> students = new ArrayList<>();

        for (int rowIndex = FIRST_STUDENT_ROW; rowIndex <= sheet.getLastRowNum(); rowIndex++) {

            Row row = sheet.getRow(rowIndex);
            if (row == null) // Excel can have sparse rows
                continue;

            var nameOpt = getCellValue(row, NAME_COLUMN);
            var emailOpt = getCellValue(row, EMAIL_COLUMN);
            var laboratoryOpt = getCellValue(row, LABORATORY_COLUMN);

            if (nameOpt.isEmpty()) {
                issuesTracker.notifyMissingName(rowIndex + 1);
                continue;
            }

            if (emailOpt.isEmpty()) {
                issuesTracker.notifyMissingEmail(rowIndex + 1);
                continue;
            }

            var sanitizedGroupOpt = sanitizeGroup(laboratoryOpt);

            var student = new Student(row.getRowNum() + 1, emailOpt.get(), nameOpt.get(), sanitizedGroupOpt);

            students.add(student);
        }

        return students;
    }

    private static Optional<String> getCellValue(Row row, int columnIndex) {
        Objects.requireNonNull(row, "row can't be null");

        Cell cell = row.getCell(columnIndex);

        if (cell == null || cell.getCellType() != STRING)
            return Optional.empty();

        String cellValue = cell.getStringCellValue().trim();
        return cellValue.isBlank() ? Optional.empty() : Optional.of(cellValue);
    }

    /**
     * Extracts the group ID from the laboratory string used in SIES files.
     *
     * Removes the "Prácticas de Laboratorio-" prefix.
     *
     * Examples:
     * "Prácticas de Laboratorio-01" -> "01"
     * "Prácticas de Laboratorio-Inglés-02" -> "Inglés-02"
     * "Prácticas de Laboratorio-Ing-03" -> "Ing-03"
     *
     * @param laboratoryOpt The laboratory string to extract the group ID from.
     * @return The extracted group ID. If the laboratory string is empty, returns an empty Optional.
     * @throws InvalidStudentFormatException If the laboratory string does not start with the expected prefix.
     */
    private static Optional<String> sanitizeGroup(Optional<String> laboratoryOpt) throws InvalidStudentFormatException {

        if (laboratoryOpt.isEmpty())
            return Optional.empty();

        String laboratory = laboratoryOpt.get();

        if (!laboratory.startsWith(LAB_PREFIX))
            throw new InvalidStudentFormatException(
                    "Laboratory must start with '" + LAB_PREFIX + "'. Value: '" + laboratory + "'");
        String group = laboratory.substring(LAB_PREFIX.length());

        return Optional.of(group);
    }

    /**
     * Exception thrown when the SIES Excel file format is invalid or does not match the expected structure.
     */
    public static class InvalidStudentFormatException extends Exception {
        public InvalidStudentFormatException(String message) {
            super(message);
        }
    }
}
